# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Basic Infosec assembly (0x86)
email: akanane@abcit.fr
description: >- # this means to ignore newlines until "baseurl:"
 During my hacking adventures, i faced many situations where i had to go deeper than high level code to make it.
 And i was a mess when it comes to assembly (it's still the case today).
 I hope this blog helps new bloods in infosec struggling with the concept of shellcoding.
 This blog was initially created for completing the requirements of the SecurityTube.
 Linux Assembly Expert (x86) certification. Student ID: SLAE-1203
baseurl: "/SLA32" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aminekanane
github_username:  Aminekanane

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
